project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "imgs/**"

website:
  title: "高専3年 情報処理"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: key-typing.qmd
        text: "キータイピング"
      - href: shortcuts.qmd
        text: "ショートカット"
      - href: collections.qmd
        text: "速習：コレクション"
      - href: list.qmd
        text: "listあらためて"
      - href: dict.qmd
        text: "dictあらためて"
      - href: variables.qmd
        text: "変数と代入"
      - href: numpy.qmd
        text: "NumPy入門"
      - href: vector_matrix.qmd
        text: "ベクトルと行列"
      - href: visualize.qmd
        text: "データの可視化"
      - href: api.qmd
        text: "APIでデータ取得"
