project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "imgs/**"
    - "data/**"
    - "iframes/**"
    - "libs/**"

website:
  title: "情報処理"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: key-typing.qmd
        text: "キータイピング"
      - href: shortcuts.qmd
        text: "ショートカット"
      - href: collections.qmd
        text: "速習：コレクション"
      - href: list.qmd
        text: "listあらためて"
      - href: dict.qmd
        text: "dictあらためて"
      - href: variables.qmd
        text: "変数と代入"
      - href: numpy.qmd
        text: "NumPy入門"
      - href: vector_matrix.qmd
        text: "ベクトルと行列"
      - href: visualize.qmd
        text: "データの可視化"
      - href: matplotlib.qmd
        text: "matplotlib入門"
      - href: pandas.qmd
        text: "Pandas入門"
      - href: plotly.qmd
        text: "Plotly入門"
      - href: api.qmd
        text: "APIでデータ取得"
      - href: api-viz.qmd
        text: "APIデータを可視化する"
      - href: wiki-api.qmd
        text: "Wikipedia APIリファレンス"
      - href: tokyo-api.qmd
        text: "東京都オープンデータAPI"
